/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check — no auth required */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single exercise-library entry by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exercise found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exercise"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No exercise with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's profile + billing status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetMeResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Permanently delete the current user's account and app data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteMyAccountResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/cancellation-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a cancellation reason (beta preview — no real subscription exists yet) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        reasonCode: "TOO_EXPENSIVE" | "NOT_SEEING_RESULTS" | "PLAN_TOO_DEMANDING" | "PLAN_TOO_EASY" | "TECHNICAL_ISSUES" | "OTHER";
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmitCancellationFeedbackResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/notification-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's wake / evening session times */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationTimes"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user's wake / evening session times */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        wakeTimeMinutes: number;
                        eveningTimeMinutes: number;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationTimes"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit onboarding answers — screens for crisis/red-flag/cooldown, else kicks off async regime generation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        answers: {
                            age: number;
                            /** @enum {string} */
                            goalType: "INJURY_RECOVERY" | "STRENGTH" | "MOBILITY" | "GENERAL_FITNESS";
                            conditionFlags: string[];
                            /** @enum {string} */
                            injurySeverity: "none" | "mild" | "moderate" | "severe";
                            redFlags: {
                                severeSuddenPain: boolean;
                                numbnessOrTingling: boolean;
                                recentTrauma: boolean;
                                recentSurgery: boolean;
                                pregnancyRelated: boolean;
                                cardiacSymptomsWithExertion: boolean;
                            };
                        };
                        targetMovement: string;
                        symptomsText: string;
                        lifestyleContextText: string;
                        wakeTimeMinutes?: number;
                        eveningTimeMinutes?: number;
                        availableEquipment?: ("BODY_ONLY" | "MACHINE" | "OTHER" | "FOAM_ROLL" | "KETTLEBELLS" | "DUMBBELL" | "CABLE" | "BARBELL" | "BANDS" | "MEDICINE_BALL" | "EXERCISE_BALL" | "EZ_CURL_BAR")[];
                    };
                };
            };
            responses: {
                /** @description Always 200 — all four outcomes (crisis_detected/red_flagged/cooldown_active/job_created) are successful screening results, not errors. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingSubmitCrisisResponse"] | components["schemas"]["OnboardingSubmitRedFlaggedResponse"] | components["schemas"]["OnboardingSubmitCooldownResponse"] | components["schemas"]["OnboardingSubmitJobCreatedResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll a regime-generation job's status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingJobStatusResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regimes/{regimeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a regime by id, with its exercise list and (if present) source preset */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    regimeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Regime"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Regime belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No regime with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regimes/{regimeId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a DRAFT regime — optionally with edited exercises, runs structural + clinical validation first */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    regimeId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        exercises?: {
                            exerciseId: string;
                            sets?: number;
                            reps?: number;
                            durationSeconds?: number;
                            frequency?: string;
                            /** @enum {string} */
                            sessionSlot: "MORNING" | "EVENING";
                        }[];
                    };
                };
            };
            responses: {
                /** @description Activated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivateRegimeResponse"];
                    };
                };
                /** @description Not a DRAFT, or failed structural/clinical validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Regime belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No regime with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regimes/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current user's active regime (self-service 'start over') */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        reasonCode: "GOALS_CHANGED" | "STARTING_OVER" | "OTHER";
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Ended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RestartRegimeResponse"];
                    };
                };
                /** @description No active regime to restart */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's session logs, most recent first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionLogs"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Log today's pain/exertion check-in — runs the real-time escalation monitor inline */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        painScore: number;
                        /** @default false */
                        flag?: boolean;
                        perceivedExertion?: number;
                    };
                };
            };
            responses: {
                /** @description Logged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateSessionLogResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No active regime to log against */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already logged today */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-sessions/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the Today screen needs: active regime, today's sessions, today's log, current streak */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutSessionToday"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-sessions/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a workout session complete */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompleteWorkoutSessionResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No workout session with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pain trend, adherence %, weeks active, current streak */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgressSummary"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/streak-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last 60 days, each flagged whether >=1 session was completed */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreakCalendar"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Derived achievement list — nothing persisted */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Milestones"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adjustment-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user's adjustment events, most recent first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdjustmentEvents"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ok: boolean;
            /**
             * Format: date-time
             * @example 2026-08-21T12:00:00.000Z
             */
            timestamp: string;
        };
        ExerciseMedia: {
            instructions?: string[];
            images?: string[];
        } | null;
        Exercise: {
            id: string;
            name: string;
            /** @enum {string} */
            category: "MOBILITY" | "STRENGTH" | "STRETCH";
            targetMuscleGroups: string[];
            difficultyLevel: number;
            /** @enum {string|null} */
            equipment: "BODY_ONLY" | "MACHINE" | "OTHER" | "FOAM_ROLL" | "KETTLEBELLS" | "DUMBBELL" | "CABLE" | "BARBELL" | "BANDS" | "MEDICINE_BALL" | "EXERCISE_BALL" | "EZ_CURL_BAR" | null;
            contraindications: string[];
            progressionGroup: string | null;
            media: components["schemas"]["ExerciseMedia"];
            source: string;
            externalId: string | null;
        };
        GetMeResponse: {
            /** @enum {string} */
            goalType: "INJURY_RECOVERY" | "STRENGTH" | "MOBILITY" | "GENERAL_FITNESS";
            /** Format: date-time */
            createdAt: string;
            wakeTimeMinutes: number | null;
            eveningTimeMinutes: number | null;
            billing: {
                trialActive: boolean;
                /** Format: date-time */
                firstAdjustmentAt: string | null;
            };
        };
        SubmitCancellationFeedbackResponse: {
            /** @enum {boolean} */
            received: true;
        };
        NotificationTimes: {
            wakeTimeMinutes: number | null;
            eveningTimeMinutes: number | null;
        };
        DeleteMyAccountResponse: {
            /** @enum {boolean} */
            success: true;
        };
        OnboardingSubmitCrisisResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "crisis_detected";
            reasons: string[];
        };
        OnboardingSubmitRedFlaggedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "red_flagged";
            reasons: string[];
        };
        OnboardingSubmitCooldownResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "cooldown_active";
            /** Format: date-time */
            regimeCreatedAt: string;
        };
        OnboardingSubmitJobCreatedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "job_created";
            jobId: string;
        };
        OnboardingJobStatusResponse: {
            id: string;
            /** @enum {string} */
            status: "PENDING" | "COMPLETE" | "FAILED";
            resultRegimeId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        Regime: {
            id: string;
            userId: string;
            versionNumber: number;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            createdBy: "AGENT" | "USER_EDITED" | "PRESET_FALLBACK";
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "SUPERSEDED" | "ENDED";
            endReason: string | null;
            sourcePresetId: string | null;
            sourcePreset: {
                id: string;
                name: string;
                description: string | null;
                /** @enum {string|null} */
                riskTier: "GENERAL" | "LIGHT_INJURY" | "HEAVIER_CHRONIC_ELDERLY" | null;
                /** Format: date-time */
                createdAt: string;
                /** @enum {string} */
                kind: "FALLBACK" | "SKELETON";
                /** @enum {string|null} */
                goalType: "INJURY_RECOVERY" | "STRENGTH" | "MOBILITY" | "GENERAL_FITNESS" | null;
                bodyRegionTags: string[];
                slots: {
                    id: string;
                    presetId: string;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                    orderIndex: number;
                    label: string;
                    /** @enum {string|null} */
                    exerciseCategory: "MOBILITY" | "STRENGTH" | "STRETCH" | null;
                    muscleGroupTags: string[];
                    maxDifficulty: number | null;
                    suggestedSets: number | null;
                    suggestedReps: number | null;
                    suggestedDurationSeconds: number | null;
                    suggestedFrequency: string | null;
                    rationale: string | null;
                }[];
            } | null;
            parentRegimeId: string | null;
            exerciseList: {
                id: string;
                regimeId: string;
                exerciseId: string;
                sets: number | null;
                reps: number | null;
                durationSeconds: number | null;
                frequency: string | null;
                /** @enum {string} */
                sessionSlot: "MORNING" | "EVENING";
                orderIndex: number;
                exercise: components["schemas"]["Exercise"];
            }[];
        };
        ActivateRegimeResponse: {
            regimeId: string;
            exerciseCount: number;
        };
        RestartRegimeResponse: {
            /** @enum {boolean} */
            success: true;
        };
        SessionLog: {
            id: string;
            userId: string;
            regimeVersionId: string;
            /** Format: date-time */
            loggedAt: string;
            painScore: number;
            mobilityStrengthIndicator?: unknown;
            completed: boolean;
            perceivedExertion: number | null;
            flag: boolean;
        };
        SessionLogs: components["schemas"]["SessionLog"][];
        CreateSessionLogResponse: {
            sessionLogId: string;
            escalation: {
                /** @enum {string} */
                action: "none" | "hold" | "flag_for_review" | "rollback";
                reasons: string[];
            };
        };
        WorkoutSession: {
            id: string;
            userId: string;
            regimeVersionId: string;
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            slot: "MORNING" | "EVENING";
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        WorkoutSessionToday: {
            regime: {
                id: string;
                userId: string;
                versionNumber: number;
                /** Format: date-time */
                createdAt: string;
                /** @enum {string} */
                createdBy: "AGENT" | "USER_EDITED" | "PRESET_FALLBACK";
                /** @enum {string} */
                status: "DRAFT" | "ACTIVE" | "SUPERSEDED" | "ENDED";
                endReason: string | null;
                sourcePresetId: string | null;
                parentRegimeId: string | null;
                exerciseList: {
                    id: string;
                    regimeId: string;
                    exerciseId: string;
                    sets: number | null;
                    reps: number | null;
                    durationSeconds: number | null;
                    frequency: string | null;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                    orderIndex: number;
                    exercise: components["schemas"]["Exercise"];
                }[];
            } | null;
            sessions: components["schemas"]["WorkoutSession"][];
            todaysLog: components["schemas"]["SessionLog"] & unknown;
            streak: number;
        };
        CompleteWorkoutSessionResponse: {
            workoutSessionId: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        ProgressSummary: {
            painTrend: {
                date: string;
                painScore: number;
            }[];
            adherencePct: number | null;
            completedSessions: number;
            totalSessions: number;
            weeksActive: number;
            streak: number;
        };
        StreakCalendar: {
            days: {
                date: string;
                completed: boolean;
            }[];
            streak: number;
        };
        Milestones: {
            id: string;
            label: string;
            description: string;
        }[];
        AdjustmentEvent: {
            id: string;
            userId: string;
            fromRegimeVersionId: string;
            toRegimeVersionId: string;
            /** Format: date-time */
            triggeredAt: string;
            /** @enum {string} */
            triggerType: "SCHEDULED_ADJUSTMENT" | "ESCALATION_ROLLBACK";
            trailingWindowUsed: number;
            rationale: string;
            wasReversed: boolean;
            fromRegime: {
                versionNumber: number;
            };
            toRegime: {
                versionNumber: number;
            };
        };
        AdjustmentEvents: components["schemas"]["AdjustmentEvent"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
