/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check — no auth required */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single exercise-library entry by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exerciseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exercise found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exercise"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No exercise with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's profile + billing status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetMeResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Permanently delete the current user's account and app data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteMyAccountResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/cancellation-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a cancellation reason (beta preview — no real subscription exists yet) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        reasonCode: "TOO_EXPENSIVE" | "NOT_SEEING_RESULTS" | "PLAN_TOO_DEMANDING" | "PLAN_TOO_EASY" | "TECHNICAL_ISSUES" | "OTHER";
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmitCancellationFeedbackResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/notification-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's wake / evening session times */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationTimes"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user's wake / evening session times */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        wakeTimeMinutes: number;
                        eveningTimeMinutes: number;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationTimes"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit onboarding answers — screens for crisis/red-flag/cooldown, else kicks off async regime generation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        answers: {
                            age: number;
                            /** @enum {string} */
                            goalType: "INJURY_RECOVERY" | "STRENGTH" | "MOBILITY" | "GENERAL_FITNESS";
                            conditionFlags: string[];
                            /** @enum {string} */
                            injurySeverity: "none" | "mild" | "moderate" | "severe";
                            redFlags: {
                                severeSuddenPain: boolean;
                                numbnessOrTingling: boolean;
                                recentTrauma: boolean;
                                recentSurgery: boolean;
                                pregnancyRelated: boolean;
                                cardiacSymptomsWithExertion: boolean;
                            };
                        };
                        targetMovement: string;
                        symptomsText: string;
                        lifestyleContextText: string;
                        wakeTimeMinutes?: number;
                        eveningTimeMinutes?: number;
                        availableEquipment?: ("BODY_ONLY" | "MACHINE" | "OTHER" | "FOAM_ROLL" | "KETTLEBELLS" | "DUMBBELL" | "CABLE" | "BARBELL" | "BANDS" | "MEDICINE_BALL" | "EXERCISE_BALL" | "EZ_CURL_BAR")[];
                    };
                };
            };
            responses: {
                /** @description Always 200 — all four outcomes (crisis_detected/red_flagged/cooldown_active/job_created) are successful screening results, not errors. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingSubmitCrisisResponse"] | components["schemas"]["OnboardingSubmitRedFlaggedResponse"] | components["schemas"]["OnboardingSubmitCooldownResponse"] | components["schemas"]["OnboardingSubmitJobCreatedResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll a regime-generation job's status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnboardingJobStatusResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regimes/{regimeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a regime by id, with its exercise list and (if present) source preset */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    regimeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Regime"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Regime belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No regime with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regimes/{regimeId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a DRAFT regime — optionally with edited exercises, runs structural + clinical validation first */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    regimeId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        exercises?: {
                            exerciseId: string;
                            sets?: number;
                            reps?: number;
                            durationSeconds?: number;
                            frequency?: string;
                            /** @enum {string} */
                            sessionSlot: "MORNING" | "EVENING";
                        }[];
                    };
                };
            };
            responses: {
                /** @description Activated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivateRegimeResponse"];
                    };
                };
                /** @description Not a DRAFT, or failed structural/clinical validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Regime belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No regime with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regimes/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current user's active regime (self-service 'start over') */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        reasonCode: "GOALS_CHANGED" | "STARTING_OVER" | "OTHER";
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Ended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RestartRegimeResponse"];
                    };
                };
                /** @description No active regime to restart */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's session logs, most recent first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionLogs"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Log today's pain/exertion check-in — runs the real-time escalation monitor inline */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        painScore: number;
                        /** @default false */
                        flag?: boolean;
                        perceivedExertion?: number;
                    };
                };
            };
            responses: {
                /** @description Logged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateSessionLogResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No active regime to log against */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already logged today */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-sessions/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the Today screen needs: active regime, today's sessions, today's log, current streak */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkoutSessionToday"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-sessions/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a workout session complete */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompleteWorkoutSessionResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session belongs to another user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No workout session with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pain trend, adherence %, weeks active, current streak */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgressSummary"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/streak-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last 60 days, each flagged whether >=1 session was completed */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreakCalendar"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Derived achievement list — nothing persisted */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Milestones"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adjustment-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user's adjustment events, most recent first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdjustmentEvents"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/flagged-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users with an escalation rollback, a 'made it worse' flag, or a failed regime-generation job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminFlaggedUsers"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/manual-hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle manual hold for a user — both the escalation monitor and Flow B skip a held user */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        manualHold: boolean;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminSetManualHoldResponse"];
                    };
                };
                /** @description A reason is required to enable manual hold */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activation funnel, adverse events, flow failure counts, reversal rate */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminMetrics"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models available for a dry run */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AvailableModels"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved test fixtures */
        get: {
            parameters: {
                query?: {
                    type?: "ONBOARDING" | "ADJUSTMENT";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestFixtures"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Save a new test fixture — payload validated against the real onboarding/adjustment schema */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string;
                        /** @enum {string} */
                        type: "ONBOARDING" | "ADJUSTMENT";
                        payload?: unknown;
                    };
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestFixture"];
                    };
                };
                /** @description Payload doesn't match the declared type's shape */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/fixtures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a test fixture (blocked if any test run references it) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteByIdResponse"];
                    };
                };
                /** @description Referenced by existing test runs */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/test-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the last 50 test runs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestRunSummaries"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Dry-run Flow A or Flow B against a fixture with a chosen model */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        fixtureId: string;
                        model: string;
                    };
                };
            };
            responses: {
                /** @description Run complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestRunDetail"];
                    };
                };
                /** @description Unknown model */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Fixture not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/test-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a test run's full detail, including its LLM call trace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestRunDetail"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No test run with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/llm-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List logged LLM calls (production and admin-test), most recent first */
        get: {
            parameters: {
                query?: {
                    flow?: "FLOW_A_DRAFT" | "FLOW_B_ADJUST" | "FREE_TEXT_CLASSIFIER";
                    source?: "PRODUCTION" | "ADMIN_TEST";
                    model?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmCalls"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scenarios with aggregated cost and latest cycle status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScenarioSummaries"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Start a scenario — cycle 0 is a real Flow A dry run against an ONBOARDING fixture */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        fixtureId: string;
                        model: string;
                        name: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScenarioStartResponse"];
                    };
                };
                /** @description Unknown model, or fixture isn't ONBOARDING type */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Fixture not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/scenarios/{id}/next-cycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run one more synthetic Flow B cycle against a scenario's most recent valid cycle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        painPattern: "IMPROVING" | "PLATEAUING" | "WORSENING" | "CONTRADICTORY";
                        /** @default 7 */
                        days?: number;
                        model: string;
                    };
                };
            };
            responses: {
                /** @description Cycle complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScenarioCycleResponse"];
                    };
                };
                /** @description Unknown model, no prior cycle, or the previous cycle isn't VALID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Scenario not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/experiments/scenarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scenario's full cycle chain, diffs, and flattened pain timeline */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScenarioDetailResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No scenario with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a scenario and every cycle/LLM-call trace under it (cascades) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteByIdResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ok: boolean;
            /**
             * Format: date-time
             * @example 2026-08-21T12:00:00.000Z
             */
            timestamp: string;
        };
        ExerciseMedia: {
            instructions?: string[];
            images?: string[];
        } | null;
        Exercise: {
            id: string;
            name: string;
            /** @enum {string} */
            category: "MOBILITY" | "STRENGTH" | "STRETCH";
            targetMuscleGroups: string[];
            difficultyLevel: number;
            /** @enum {string|null} */
            equipment: "BODY_ONLY" | "MACHINE" | "OTHER" | "FOAM_ROLL" | "KETTLEBELLS" | "DUMBBELL" | "CABLE" | "BARBELL" | "BANDS" | "MEDICINE_BALL" | "EXERCISE_BALL" | "EZ_CURL_BAR" | null;
            contraindications: string[];
            progressionGroup: string | null;
            media: components["schemas"]["ExerciseMedia"];
            source: string;
            externalId: string | null;
        };
        GetMeResponse: {
            /** @enum {string} */
            goalType: "INJURY_RECOVERY" | "STRENGTH" | "MOBILITY" | "GENERAL_FITNESS";
            /** Format: date-time */
            createdAt: string;
            wakeTimeMinutes: number | null;
            eveningTimeMinutes: number | null;
            billing: {
                trialActive: boolean;
                /** Format: date-time */
                firstAdjustmentAt: string | null;
            };
        };
        SubmitCancellationFeedbackResponse: {
            /** @enum {boolean} */
            received: true;
        };
        NotificationTimes: {
            wakeTimeMinutes: number | null;
            eveningTimeMinutes: number | null;
        };
        DeleteMyAccountResponse: {
            /** @enum {boolean} */
            success: true;
        };
        OnboardingSubmitCrisisResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "crisis_detected";
            reasons: string[];
        };
        OnboardingSubmitRedFlaggedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "red_flagged";
            reasons: string[];
        };
        OnboardingSubmitCooldownResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "cooldown_active";
            /** Format: date-time */
            regimeCreatedAt: string;
        };
        OnboardingSubmitJobCreatedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "job_created";
            jobId: string;
        };
        OnboardingJobStatusResponse: {
            id: string;
            /** @enum {string} */
            status: "PENDING" | "COMPLETE" | "FAILED";
            resultRegimeId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        Regime: {
            id: string;
            userId: string;
            versionNumber: number;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            createdBy: "AGENT" | "USER_EDITED" | "PRESET_FALLBACK";
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "SUPERSEDED" | "ENDED";
            endReason: string | null;
            sourcePresetId: string | null;
            sourcePreset: {
                id: string;
                name: string;
                description: string | null;
                /** @enum {string|null} */
                riskTier: "GENERAL" | "LIGHT_INJURY" | "HEAVIER_CHRONIC_ELDERLY" | null;
                /** Format: date-time */
                createdAt: string;
                /** @enum {string} */
                kind: "FALLBACK" | "SKELETON";
                /** @enum {string|null} */
                goalType: "INJURY_RECOVERY" | "STRENGTH" | "MOBILITY" | "GENERAL_FITNESS" | null;
                bodyRegionTags: string[];
                slots: {
                    id: string;
                    presetId: string;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                    orderIndex: number;
                    label: string;
                    /** @enum {string|null} */
                    exerciseCategory: "MOBILITY" | "STRENGTH" | "STRETCH" | null;
                    muscleGroupTags: string[];
                    maxDifficulty: number | null;
                    suggestedSets: number | null;
                    suggestedReps: number | null;
                    suggestedDurationSeconds: number | null;
                    suggestedFrequency: string | null;
                    rationale: string | null;
                }[];
            } | null;
            parentRegimeId: string | null;
            exerciseList: {
                id: string;
                regimeId: string;
                exerciseId: string;
                sets: number | null;
                reps: number | null;
                durationSeconds: number | null;
                frequency: string | null;
                /** @enum {string} */
                sessionSlot: "MORNING" | "EVENING";
                orderIndex: number;
                exercise: components["schemas"]["Exercise"];
            }[];
        };
        ActivateRegimeResponse: {
            regimeId: string;
            exerciseCount: number;
        };
        RestartRegimeResponse: {
            /** @enum {boolean} */
            success: true;
        };
        SessionLog: {
            id: string;
            userId: string;
            regimeVersionId: string;
            /** Format: date-time */
            loggedAt: string;
            painScore: number;
            mobilityStrengthIndicator?: unknown;
            completed: boolean;
            perceivedExertion: number | null;
            flag: boolean;
        };
        SessionLogs: components["schemas"]["SessionLog"][];
        CreateSessionLogResponse: {
            sessionLogId: string;
            escalation: {
                /** @enum {string} */
                action: "none" | "hold" | "flag_for_review" | "rollback";
                reasons: string[];
            };
        };
        WorkoutSession: {
            id: string;
            userId: string;
            regimeVersionId: string;
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            slot: "MORNING" | "EVENING";
            /** Format: date-time */
            scheduledAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        WorkoutSessionToday: {
            regime: {
                id: string;
                userId: string;
                versionNumber: number;
                /** Format: date-time */
                createdAt: string;
                /** @enum {string} */
                createdBy: "AGENT" | "USER_EDITED" | "PRESET_FALLBACK";
                /** @enum {string} */
                status: "DRAFT" | "ACTIVE" | "SUPERSEDED" | "ENDED";
                endReason: string | null;
                sourcePresetId: string | null;
                parentRegimeId: string | null;
                exerciseList: {
                    id: string;
                    regimeId: string;
                    exerciseId: string;
                    sets: number | null;
                    reps: number | null;
                    durationSeconds: number | null;
                    frequency: string | null;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                    orderIndex: number;
                    exercise: components["schemas"]["Exercise"];
                }[];
            } | null;
            sessions: components["schemas"]["WorkoutSession"][];
            todaysLog: components["schemas"]["SessionLog"] & unknown;
            streak: number;
        };
        CompleteWorkoutSessionResponse: {
            workoutSessionId: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        ProgressSummary: {
            painTrend: {
                date: string;
                painScore: number;
            }[];
            adherencePct: number | null;
            completedSessions: number;
            totalSessions: number;
            weeksActive: number;
            streak: number;
        };
        StreakCalendar: {
            days: {
                date: string;
                completed: boolean;
            }[];
            streak: number;
        };
        Milestones: {
            id: string;
            label: string;
            description: string;
        }[];
        AdjustmentEvent: {
            id: string;
            userId: string;
            fromRegimeVersionId: string;
            toRegimeVersionId: string;
            /** Format: date-time */
            triggeredAt: string;
            /** @enum {string} */
            triggerType: "SCHEDULED_ADJUSTMENT" | "ESCALATION_ROLLBACK";
            trailingWindowUsed: number;
            rationale: string;
            wasReversed: boolean;
            fromRegime: {
                versionNumber: number;
            };
            toRegime: {
                versionNumber: number;
            };
        };
        AdjustmentEvents: components["schemas"]["AdjustmentEvent"][];
        AdminFlaggedUsers: {
            user: {
                id: string;
                /** @enum {string} */
                goalType: "INJURY_RECOVERY" | "STRENGTH" | "MOBILITY" | "GENERAL_FITNESS";
                /** @enum {string} */
                riskTier: "GENERAL" | "LIGHT_INJURY" | "HEAVIER_CHRONIC_ELDERLY";
                manualHold: boolean;
                manualHoldReason: string | null;
                /** Format: date-time */
                createdAt: string;
            };
            reasons: string[];
            /** Format: date-time */
            mostRecent: string;
        }[];
        AdminSetManualHoldResponse: {
            userId: string;
            manualHold: boolean;
            manualHoldReason: string | null;
        };
        AdminMetrics: {
            activationFunnel: {
                totalUsers: number;
                regimeGenerated: number;
                regimeActivated: number;
                loggedAtLeastOnce: number;
            };
            adverseEvents: {
                flaggedSessionLogs: number;
                escalationRollbacks: number;
            };
            flowFailures: {
                flowAJobsTotal: number;
                flowAJobsFailed: number;
                flowBScheduledAdjustments: number;
                flowBScheduledHolds: number;
            };
            reversalRate: {
                totalAdjustmentEvents: number;
                markedReversed: number;
                note: string;
            };
        };
        AvailableModels: {
            id: string;
            label: string;
            inputPerMTok: number;
            outputPerMTok: number;
        }[];
        TestFixture: {
            id: string;
            name: string;
            description: string | null;
            /** @enum {string} */
            type: "ONBOARDING" | "ADJUSTMENT";
            payload?: unknown;
            /** Format: date-time */
            createdAt: string;
        };
        TestFixtures: components["schemas"]["TestFixture"][];
        DeleteByIdResponse: {
            id: string;
        };
        LlmCall: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            flow: "FLOW_A_DRAFT" | "FLOW_B_ADJUST" | "FREE_TEXT_CLASSIFIER";
            /** @enum {string} */
            source: "PRODUCTION" | "ADMIN_TEST";
            model: string;
            groupId: string;
            sequenceIndex: number;
            userId: string | null;
            testRunId: string | null;
            inputTokens: number;
            outputTokens: number;
            latencyMs: number;
            costUsd: string | null;
            stopReason: string | null;
            success: boolean;
            errorMessage: string | null;
            requestJson?: unknown;
            responseJson?: unknown;
        };
        LlmCalls: components["schemas"]["LlmCall"][];
        TestRunDetail: {
            id: string;
            fixtureId: string | null;
            /** @enum {string} */
            flow: "FLOW_A_DRAFT" | "FLOW_B_ADJUST" | "FREE_TEXT_CLASSIFIER";
            model: string;
            /** @enum {string} */
            status: "RUNNING" | "VALID" | "INVALID" | "ERROR";
            resultJson?: unknown;
            createdByUserId: string;
            /** Format: date-time */
            createdAt: string;
            scenarioId: string | null;
            cycleIndex: number | null;
            inputJson?: unknown;
            llmCalls: components["schemas"]["LlmCall"][];
            fixture: components["schemas"]["TestFixture"] & unknown;
            exerciseNames: {
                [key: string]: {
                    name: string;
                    category: string;
                };
            };
        };
        TestRunSummary: {
            id: string;
            fixtureId: string | null;
            /** @enum {string} */
            flow: "FLOW_A_DRAFT" | "FLOW_B_ADJUST" | "FREE_TEXT_CLASSIFIER";
            model: string;
            /** @enum {string} */
            status: "RUNNING" | "VALID" | "INVALID" | "ERROR";
            resultJson?: unknown;
            createdByUserId: string;
            /** Format: date-time */
            createdAt: string;
            scenarioId: string | null;
            cycleIndex: number | null;
            inputJson?: unknown;
            fixture: {
                name: string;
            } | null;
            llmCalls: {
                costUsd: string | null;
            }[];
        };
        TestRunSummaries: components["schemas"]["TestRunSummary"][];
        ScenarioStartResponse: {
            scenario: {
                id: string;
                name: string;
                description: string | null;
                /** Format: date-time */
                createdAt: string;
                createdByUserId: string;
            };
            testRun: components["schemas"]["TestRunDetail"];
        };
        ScenarioCycleResponse: components["schemas"]["TestRunDetail"] & {
            diffFromPrevious: {
                exerciseId: string;
                /** @enum {string} */
                change: "added" | "removed" | "changed" | "unchanged";
                before?: {
                    exerciseId: string;
                    sets?: number;
                    reps?: number;
                    durationSeconds?: number;
                    frequency?: string;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                };
                after?: {
                    exerciseId: string;
                    sets?: number;
                    reps?: number;
                    durationSeconds?: number;
                    frequency?: string;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                };
                changedFields?: string[];
            }[] | null;
            diffFromOriginal: {
                exerciseId: string;
                /** @enum {string} */
                change: "added" | "removed" | "changed" | "unchanged";
                before?: {
                    exerciseId: string;
                    sets?: number;
                    reps?: number;
                    durationSeconds?: number;
                    frequency?: string;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                };
                after?: {
                    exerciseId: string;
                    sets?: number;
                    reps?: number;
                    durationSeconds?: number;
                    frequency?: string;
                    /** @enum {string} */
                    sessionSlot: "MORNING" | "EVENING";
                };
                changedFields?: string[];
            }[] | null;
        };
        ScenarioSummaries: {
            id: string;
            name: string;
            description: string | null;
            /** Format: date-time */
            createdAt: string;
            cycleCount: number;
            /** @enum {string|null} */
            latestStatus: "RUNNING" | "VALID" | "INVALID" | "ERROR" | null;
            totalCost: number;
        }[];
        ScenarioDetailResponse: {
            scenario: {
                id: string;
                name: string;
                description: string | null;
                /** Format: date-time */
                createdAt: string;
            };
            cycles: components["schemas"]["ScenarioCycleResponse"][];
            painTimeline: {
                simulatedDay: number;
                painScore: number;
                madeItWorseFlag: boolean;
                cycleIndex: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
